### ISSUE TITLE
Visualization Resource Not Found

### ISSUE THREAD

**Issue by revolutionarily** [ClickInsight/community-visualizations#5]
Added a Radar Chart two days ago, chart was working until it suddenly wasn't. The chart now shows an empty white box.

Tried to add the chart again, was given the error as shown below:

![image](https://user-images.githubusercontent.com/75514910/144342941-fdb240fb-dc3e-4664-8cda-f1fd2d88b2c0.png)

What am I doing wrongly? Please help! Thank you very much!

**Comment by Omar-Castillo** [comment]
@revolutionarily How were you able to resolve this issue? We started having this issue as well.

![image](https://user-images.githubusercontent.com/35577882/150725459-46f84f4a-3d4e-4d99-9765-50e06d66065d.png)
